import { Cannon, Blaster, Torpedo, Missile, Primary} from './models/primary';
import { Entity } from './models/entity';

export class PRIMARY {

  static getSystem(type:string, entity:Entity):Primary {
    let system_type = PRIMARY.TYPE[type]["system_type"];
    return new system_type( entity, PRIMARY.TYPE[type]);
  }

  public static TYPE = {
    "Cannon": {
      system_type: Cannon,
      damage: 1,
      range: 1,
      speed: 400,
      fire_rate: 1,
      radius: 15,
      bullet_count: 1,
      bullet_angle: 0,
      bullet_offset: 0,
      bullet_mesh: "Cannon",
    },
    "Cannon 2.0": {
      system_type: Cannon,
      damage: 1,
      range: 1,
      speed: 400,
      fire_rate: 1,
      radius: 15,
      bullet_count: 2,
      bullet_angle: Math.PI/6,
      bullet_offset: 0,
      bullet_mesh: "Cannon",
      unlock_key: "max_kills_Cannon",
      unlock_count: 200,
    },
    "Cannon 3.0": {
      system_type: Cannon,
      damage: 1,
      range: 1,
      speed: 400,
      fire_rate: 1,
      radius: 15,
      bullet_count: 3,
      bullet_angle: Math.PI/4,
      bullet_offset: 0,
      bullet_mesh: "Cannon",
      unlock_key: "max_kills_Cannon 2.0",
      unlock_count: 300
    },
    "Blaster": {
      system_type: Blaster,
      damage: 1.2,
      range: 1.2,
      speed: 350,
      fire_rate: 0.8,
      radius: 15,
      bullet_count: 1,
      bullet_angle: 0,
      bullet_offset: 0,
      bullet_mesh: "Blaster"
    },
    "Blaster 2.0": {
      system_type: Blaster,
      damage: 1.2,
      range: 1.2,
      speed: 350,
      fire_rate: 0.8,
      radius: 15,
      bullet_count: 2,
      bullet_angle: 0,
      bullet_offset: 30,
      bullet_mesh: "Blaster",
      unlock_key: "max_kills_Blaster",
      unlock_count: 200
    },
    "Blaster 3.0": {
      system_type: Blaster,
      damage: 1.2,
      range: 1.2,
      speed: 350,
      fire_rate: 0.8,
      radius: 15,
      bullet_count: 3,
      bullet_angle: 0,
      bullet_offset: 30,
      bullet_mesh: "Blaster",
      unlock_key: "max_kills_Blaster 2.0",
      unlock_count: 200
    },
    "Rapid": {
      system_type: Cannon,
      damage: 0.15,
      range: 0.8,
      speed: 400,
      fire_rate: 0.2,
      radius: 15,
      bullet_count: 1,
      bullet_angle: 0,
      bullet_offset: 0,
      bullet_mesh: "Cannon",
      unlock_key: "max_kills_Cannon",
      unlock_count: 750
    },
    "Beam": {
      system_type: Blaster,
      damage: 1,
      range: 1.1,
      speed: 600,
      fire_rate: 1.1,
      radius: 15,
      bullet_count: 1,
      bullet_angle: 0,
      bullet_offset: 0,
      bullet_mesh: "Beam",
      unlock_key: "max_kills_Blaster 2.0",
      unlock_count: 400
    },
    "Double Beam": {
      system_type: Blaster,
      damage: 1,
      range: 1.1,
      speed: 600,
      fire_rate: 1,
      radius: 15,
      bullet_count: 2,
      bullet_angle: 0,
      bullet_offset: 15,
      bullet_mesh: "Beam",
      unlock_key: "max_kills_Beam",
      unlock_count: 200
    },
    "Triple Beam": {
      system_type: Blaster,
      damage: 1,
      range: 1.1,
      speed: 600,
      fire_rate: 1,
      radius: 15,
      bullet_count: 3,
      bullet_angle: 0,
      bullet_offset: 15,
      bullet_mesh: "Beam",
      unlock_key: "max_kills_Double Beam",
      unlock_count: 400
    },
    "Missile": {
      system_type: Missile,
      damage: 1.2,
      range: 1.5,
      speed: 350,
      fire_rate: 0.9,
      radius: 15,
      bullet_count: 1,
      bullet_angle: 0,
      bullet_offset: 0,
      bullet_mesh: "Missile",
      unlock_key: "max_kills_Cannon",
      unlock_count: 750
    },
    "Double Missile": {
      system_type: Missile,
      damage: 1.2,
      range: 1.5,
      speed: 350,
      fire_rate: 0.9,
      radius: 15,
      bullet_count: 2,
      bullet_angle: Math.PI/6,
      bullet_offset: 15,
      bullet_mesh: "Missile",
      unlock_key: "max_kills_Missile",
      unlock_count: 750
    },
    "Triple Missile": {
      system_type: Missile,
      damage: 1.2,
      range: 1.5,
      speed: 350,
      fire_rate: 0.9,
      radius: 15,
      bullet_count: 3,
      bullet_angle: Math.PI/4,
      bullet_offset: 15,
      bullet_mesh: "Missile",
      unlock_key: "max_kills_Double Missile",
      unlock_count: 750
    },
    "Torpedo": {
      system_type: Torpedo,
      damage: 1.3,
      range: 1.2,
      speed: 400,
      fire_rate: 0.8,
      radius: 15,
      bullet_count: 1,
      bullet_angle: 0,
      bullet_offset: 0,
      blast_radius: 200,
      bullet_mesh: "Torpedo",
      unlock_key: "max_kills_Blaster 2.0",
      unlock_count: 1000
    },
    "Double Torpedo": {
      system_type: Torpedo,
      damage: 1.3,
      range: 1.2,
      speed: 400,
      fire_rate: 0.8,
      radius: 15,
      bullet_count: 2,
      bullet_angle: 0,
      bullet_offset: 15,
      blast_radius: 200,
      bullet_mesh: "Torpedo",
      unlock_key: "max_kills_Torpedo",
      unlock_count: 1000
    },
    "Triple Torpedo": {
      system_type: Torpedo,
      damage: 1.3,
      range: 1.2,
      speed: 400,
      fire_rate: 0.8,
      radius: 15,
      bullet_count: 3,
      bullet_angle: 0,
      bullet_offset: 15,
      blast_radius: 200,
      bullet_mesh: "Torpedo",
      unlock_key: "max_kills_Double Torpedo",
      unlock_count: 1000
    },
  };
}
