import { Cannon, Blaster, Torpedo, Missile, Primary} from './models/primary';
import { Entity } from './models/Entity';

export class PRIMARY {

  static getSystem(type: string, entity: Entity): Primary {
    const systemType = PRIMARY.TYPE[type]["systemType"];
    return new systemType( entity, PRIMARY.TYPE[type]);
  }

  public static TYPE = {
    "Cannon": {
      systemType: Cannon,
      damage: 1,
      range: 1,
      speed: 400,
      fireRate: 1,
      radius: 15,
      bulletCount: 1,
      bulletAngle: 0,
      bulletOffset: 0,
      bulletMesh: "Cannon",
    },
    "Cannon 2.0": {
      systemType: Cannon,
      damage: 1,
      range: 1,
      speed: 400,
      fireRate: 1,
      radius: 15,
      bulletCount: 2,
      bulletAngle: Math.PI/6,
      bulletOffset: 0,
      bulletMesh: "Cannon",
      unlockKey: "max_kills_Cannon",
      unlockCount: 200,
    },
    "Cannon 3.0": {
      systemType: Cannon,
      damage: 1,
      range: 1,
      speed: 400,
      fireRate: 1,
      radius: 15,
      bulletCount: 3,
      bulletAngle: Math.PI/4,
      bulletOffset: 0,
      bulletMesh: "Cannon",
      unlockKey: "max_kills_Cannon 2.0",
      unlockCount: 300
    },
    "Blaster": {
      systemType: Blaster,
      damage: 1.2,
      range: 1.2,
      speed: 350,
      fireRate: 0.8,
      radius: 15,
      bulletCount: 1,
      bulletAngle: 0,
      bulletOffset: 0,
      bulletMesh: "Blaster"
    },
    "Blaster 2.0": {
      systemType: Blaster,
      damage: 1.2,
      range: 1.2,
      speed: 350,
      fireRate: 0.8,
      radius: 15,
      bulletCount: 2,
      bulletAngle: 0,
      bulletOffset: 30,
      bulletMesh: "Blaster",
      unlockKey: "max_kills_Blaster",
      unlockCount: 200
    },
    "Blaster 3.0": {
      systemType: Blaster,
      damage: 1.2,
      range: 1.2,
      speed: 350,
      fireRate: 0.8,
      radius: 15,
      bulletCount: 3,
      bulletAngle: 0,
      bulletOffset: 30,
      bulletMesh: "Blaster",
      unlockKey: "max_kills_Blaster 2.0",
      unlockCount: 200
    },
    "Rapid": {
      systemType: Cannon,
      damage: 0.15,
      range: 0.8,
      speed: 400,
      fireRate: 0.2,
      radius: 15,
      bulletCount: 1,
      bulletAngle: 0,
      bulletOffset: 0,
      bulletMesh: "Cannon",
      unlockKey: "max_kills_Cannon",
      unlockCount: 750
    },
    "Beam": {
      systemType: Blaster,
      damage: 1,
      range: 1.1,
      speed: 600,
      fireRate: 1.1,
      radius: 15,
      bulletCount: 1,
      bulletAngle: 0,
      bulletOffset: 0,
      bulletMesh: "Beam",
      unlockKey: "max_kills_Blaster 2.0",
      unlockCount: 400
    },
    "Double Beam": {
      systemType: Blaster,
      damage: 1,
      range: 1.1,
      speed: 600,
      fireRate: 1,
      radius: 15,
      bulletCount: 2,
      bulletAngle: 0,
      bulletOffset: 15,
      bulletMesh: "Beam",
      unlockKey: "max_kills_Beam",
      unlockCount: 200
    },
    "Triple Beam": {
      systemType: Blaster,
      damage: 1,
      range: 1.1,
      speed: 600,
      fireRate: 1,
      radius: 15,
      bulletCount: 3,
      bulletAngle: 0,
      bulletOffset: 15,
      bulletMesh: "Beam",
      unlockKey: "max_kills_Double Beam",
      unlockCount: 400
    },
    "Missile": {
      systemType: Missile,
      damage: 1.2,
      range: 1.5,
      speed: 350,
      fireRate: 0.9,
      radius: 15,
      bulletCount: 1,
      bulletAngle: 0,
      bulletOffset: 0,
      bulletMesh: "Missile",
      unlockKey: "max_kills_Cannon",
      unlockCount: 750
    },
    "Double Missile": {
      systemType: Missile,
      damage: 1.2,
      range: 1.5,
      speed: 350,
      fireRate: 0.9,
      radius: 15,
      bulletCount: 2,
      bulletAngle: Math.PI/6,
      bulletOffset: 15,
      bulletMesh: "Missile",
      unlockKey: "max_kills_Missile",
      unlockCount: 750
    },
    "Triple Missile": {
      systemType: Missile,
      damage: 1.2,
      range: 1.5,
      speed: 350,
      fireRate: 0.9,
      radius: 15,
      bulletCount: 3,
      bulletAngle: Math.PI/4,
      bulletOffset: 15,
      bulletMesh: "Missile",
      unlockKey: "max_kills_Double Missile",
      unlockCount: 750
    },
    "Torpedo": {
      systemType: Torpedo,
      damage: 1.3,
      range: 1.2,
      speed: 400,
      fireRate: 0.8,
      radius: 15,
      bulletCount: 1,
      bulletAngle: 0,
      bulletOffset: 0,
      blastRadius: 200,
      bulletMesh: "Torpedo",
      unlockKey: "max_kills_Blaster 2.0",
      unlockCount: 1000
    },
    "Double Torpedo": {
      systemType: Torpedo,
      damage: 1.3,
      range: 1.2,
      speed: 400,
      fireRate: 0.8,
      radius: 15,
      bulletCount: 2,
      bulletAngle: 0,
      bulletOffset: 15,
      blastRadius: 200,
      bulletMesh: "Torpedo",
      unlockKey: "max_kills_Torpedo",
      unlockCount: 1000
    },
    "Triple Torpedo": {
      systemType: Torpedo,
      damage: 1.3,
      range: 1.2,
      speed: 400,
      fireRate: 0.8,
      radius: 15,
      bulletCount: 3,
      bulletAngle: 0,
      bulletOffset: 15,
      blastRadius: 200,
      bulletMesh: "Torpedo",
      unlockKey: "max_kills_Double Torpedo",
      unlockCount: 1000
    },
  };
}
