export class SHIP {
  public static TYPE = {
    'explorer1': {
      'description': `First generation of the explorer model. Designed for speed, shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 1.1,
      'shield': 1.25,
      'shieldRecharge': 1.1,
      'special': 1.1,
    },
    'explorer2': {
      'description': `Second generation of the explorer model. Designed for speed, shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 1.15,
      'shield': 1.25,
      'shieldRecharge': 1.1,
      'special': 1.15,
      'unlockKey': "maxKills_explorer1",
      'unlockCount': 500

    },
    'explorer3': {
      'description': `Third generation of the explorer model. Designed for speed, shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 1.2,
      'shield': 1.5,
      'shieldRecharge': 1.1,
      'special': 1.2,
      'unlockKey': "maxKills_explorer2",
      'unlockCount': 600
    },
    'explorer4': {
      'description': `Fourth generation of the explorer model. Designed for speed, shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 1.25,
      'shield': 1.75,
      'shieldRecharge': 1.1,
      'special': 1.25,
      'unlockKey': "maxKills_explorer3",
      'unlockCount': 700
    },
    'explorer5': {
      'description': `Fifth generation of the explorer model. Designed for speed, shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 1.3,
      'shield': 2,
      'shieldRecharge': 1.1,
      'special': 1.3,
      'unlockKey': "maxKills_explorer4",
      'unlockCount': 800
    },
    'scout1': {
      'description': `First generation of the scout model. Designed primarily for speed.`,
      'damage': 0.8,
      'range': 0.8,
      'fireRate': 1.2,
      'speed': 1.5,
      'shield': 1,
      'shieldRecharge': 1,
      'special': 1,
      'specialGrowth': 0.01
    },
    'scout2': {
      'description': `Second generation of the scout model. Designed primarily for speed.`,
      'damage': 0.8,
      'range': 0.8,
      'fireRate': 1.2,
      'speed': 1.6,
      'shield': 1,
      'shieldRecharge': 1,
      'special': 1,
      'unlockKey': "maxKills_scout1",
      'unlockCount': 500
    },
    'scout3': {
      'description': `Third generation of the scout model. Designed primarily for speed.`,
      'damage': 0.8,
      'range': 0.8,
      'fireRate': 1.2,
      'speed': 1.7,
      'shield': 1,
      'shieldRecharge': 1,
      'special': 1,
      'unlockKey': "maxKills_scout2",
      'unlockCount': 600
    },
    'scout4': {
      'description': `Fourth generation of the scout model. Designed primarily for speed.`,
      'damage': 0.8,
      'range': 0.8,
      'fireRate': 1.2,
      'speed': 1.8,
      'shield': 1,
      'shieldRecharge': 1,
      'special': 1,
      'unlockKey': "maxKills_scout3",
      'unlockCount': 700
    },
    'scout5': {
      'description': `Fifth generation of the scout model. Designed primarily for speed.`,
      'damage': 0.8,
      'range': 0.8,
      'fireRate': 1.2,
      'speed': 2,
      'shield': 1,
      'shieldRecharge': 1,
      'special': 1,
      'unlockKey': "maxKills_scout4",
      'unlockCount': 800
    },
    'gunship1': {
      'description': `First generation of the gunship model. Designed primarily for maximum damage output.`,
      'damage': 1.3,
      'range': 1.2,
      'fireRate': 0.8,
      'speed': 0.9,
      'shield': 0.9,
      'shieldRecharge': 0.9,
      'special': 1,
      'unlockKey': "maxKills",
      'unlockCount': 1000
    },
    'gunship2': {
      'description': `Second generation of the gunship model. Designed primarily for maximum damage output.`,
      'damage': 1.5,
      'range': 1.3,
      'fireRate': 0.7,
      'speed': 0.9,
      'shield': 0.9,
      'shieldRecharge': 0.9,
      'special': 1,
      'unlockKey': "maxKills_gunship1",
      'unlockCount': 600
    },
    'gunship3': {
      'description': `Third generation of the gunship model. Designed primarily for maximum damage output.`,
      'damage': 1.7,
      'range': 1.4,
      'fireRate': 0.6,
      'speed': 0.9,
      'shield': 0.9,
      'shieldRecharge': 0.9,
      'special': 1,
      'unlockKey': "maxKills_gunship2",
      'unlockCount': 700
    },
    'gunship4': {
      'description': `Fourth generation of the gunship model. Designed primarily for maximum damage output.`,
      'damage': 1.8,
      'range': 1.5,
      'fireRate': 0.5,
      'speed': 0.9,
      'shield': 0.9,
      'shieldRecharge': 0.9,
      'special': 1,
      'unlockKey': "maxKills_gunship3",
      'unlockCount': 800
    },
    'gunship5': {
      'description': `Fifth generation of the gunship model. Designed primarily for maximum damage output.`,
      'damage': 2,
      'range': 1.6,
      'fireRate': 0.4,
      'speed': 0.9,
      'shield': 0.9,
      'shieldRecharge': 0.9,
      'special': 1,
      'unlockKey': "maxKills_gunship4",
      'unlockCount': 900
    },
    'defender1': {
      'description': `First generation of the defender model. Designed for shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 0.8,
      'shield': 1.5,
      'shieldRecharge': 1.5,
      'special': 1.2,
      'unlockKey': "maxLevel",
      'unlockCount': 5
    },
    'defender2': {
      'description': `Second generation of the defender model. Designed for shielding and special ability use.`,
      'damage': 0.9,
      'range': 1.1,
      'fireRate': 0.9,
      'speed': 0.8,
      'shield': 1.6,
      'shieldRecharge': 1.6,
      'special': 1.25,
      'unlockKey': "maxKills_defender1",
      'unlockCount': 600
    },
    'defender3': {
      'description': `Third generation of the defender model. Designed for shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 0.8,
      'shield': 1.7,
      'shieldRecharge': 1.7,
      'special': 1.3,
      'unlockKey': "maxKills_defender2",
      'unlockCount': 700
    },
    'defender4': {
      'description': `Fourth generation of the defender model. Designed for shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 0.8,
      'shield': 1.8,
      'shieldRecharge': 1.8,
      'special': 1.3,
      'unlockKey': "maxKills_defender3",
      'unlockCount': 800
    },
    'defender5': {
      'description': `Fifth generation of the defender model. Designed for shielding and special ability use.`,
      'damage': 0.9,
      'range': 0.9,
      'fireRate': 1.1,
      'speed': 0.8,
      'shield': 2,
      'shieldRecharge': 2,
      'special': 1.4,
      'unlockKey': "maxKills_defender4",
      'unlockCount': 900
    },
    'fighter1': {
      'description': `First generation of the fighter model. Designed for for fighting and manueverability.`,
      'damage': 1.1,
      'range': 1.1,
      'fireRate': 0.9,
      'speed': 1.1,
      'shield': 0.8,
      'shieldRecharge': 0.9,
      'special': 0.9,
    },
    'fighter2': {
      'description': `Second generation of the fighter model. Designed for for fighting and manueverability.`,
      'damage': 1.2,
      'range': 1.2,
      'fireRate': 0.8,
      'speed': 1.2,
      'shield': 0.8,
      'shieldRecharge': 0.9,
      'special': 0.9,
      'unlockKey': "maxKills_fighter1",
      'unlockCount': 500
    },
    'fighter3': {
      'description': `Third generation of the fighter model. Designed for for fighting and manueverability.`,
      'damage': 1.3,
      'range': 1.3,
      'fireRate': 0.7,
      'speed': 1.3,
      'shield': 0.8,
      'shieldRecharge': 0.9,
      'special': 0.9,
      'unlockKey': "maxKills_fighter2",
      'unlockCount': 600
    },
    'fighter4': {
      'description': `Fourth generation of the fighter model. Designed for for fighting and manueverability.`,
      'damage': 1.4,
      'range': 1.4,
      'fireRate': 0.6,
      'speed': 1.4,
      'shield': 0.8,
      'shieldRecharge': 0.9,
      'special': 0.9,
      'unlockKey': "maxKills_fighter3",
      'unlockCount': 700
    },
    'fighter5': {
      'description': `Fifth generation of the fighter model. Designed for for fighting and manueverability.`,
      'damage': 1.5,
      'range': 1.5,
      'fireRate': 0.5,
      'speed': 1.5,
      'shield': 0.8,
      'shieldRecharge': 0.9,
      'special': 0.9,
      'unlockKey': "maxKills_fighter4",
      'unlockCount': 800
    }
  }
}
